version: '3.2'

services:
#  db:
#    image: postgres
#    ports:
#      - '5432:5432'
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_DB: slack
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#    networks:
#      - webnet
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: postgres:10
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - webnet
    env_file:
      - .env
    volumes:
    - ./database/pgdata:/var/lib/postgresql/data

networks:
    webnet:
#volumes:
#    pgdata:
